name: 'Concatenate strings with separator'
description: 'Concatenates two strings with an optional separator and exposes them as an env var'
author: 'Michael Pohl'
inputs:
  first:
    required: true
    description: 'Your first string'
  second:
    required: true
    description: 'Your second string'
  separator:
    required: false
    description: 'A string to put between the first and second provided strings'
  output-var-name: 
    required: true
    description: 'The name of the output env var'
runs:
  using: 'node12'
  main: 'dist/index.js'
